name: mobile
description: "Ecosistema Veterinario MVP - Seguimiento Post-Operatorio"
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos
  cupertino_icons: ^1.0.6

  # Gestión de Estado
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Cliente HTTP & Peticiones
  dio: ^5.4.3

  # Almacenamiento Seguro para JWT
  flutter_secure_storage: ^9.0.0

  # Cámara, Galería e Imágenes
  image_picker: ^1.1.2
  flutter_image_compress: ^2.2.0

  # Lector y Creador QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1

  # Tipografía Premium
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
